// <auto-generated />
namespace SSM_V5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init1));
        
        string IMigrationMetadata.Id
        {
            get { return "201708292359206_Init1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
