//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM_V5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoveredShift
    {
        public int CoveredId { get; set; }
        public int ShiftID { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
